CREATE DATABASE PRUEBATECNICAISP
GO

USE PRUEBATECNICAISP
GO


CREATE TABLE PRODUCTOS
(
	ID					INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE				NVARCHAR(100),
	PRECIO				DECIMAL(10,2),
	FECHACREACION		DATETIME
)
GO

SELECT * FROM PRODUCTOS